name: Auto Update Head Branch

on:
    push:
        branches:
            - 'main'

jobs:
    auto-update:
        uses: sakshi-devotess/github-action/.github/workflows/auto-update-head-branch.yml@main
        with:
          base_branch: "main"
          label_name: "auto-update"
          repository: ${{ github.repository }}
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
